// Protocol tests - no external test framework, just assert + manual harness
// disclaimer: this is test file was generated by antigravity and it is not tested yet

#include "protocol.hpp"
#include <cassert>
#include <iostream>
#include <string>
#include <cstring>
#include <vector>

#ifdef _WIN32
#include <winsock2.h>
#else
#include <arpa/inet.h>
#endif

// ===================== HELPERS =====================

static int tests_passed = 0;
static int tests_failed = 0;

#define RUN_TEST(fn) do {                                           \
    std::cout << "  Running " << #fn << "... ";                     \
    try { fn(); ++tests_passed; std::cout << "PASSED\n"; }         \
    catch (const std::exception& e) {                               \
        ++tests_failed;                                             \
        std::cout << "FAILED: " << e.what() << "\n";               \
    }                                                               \
} while(0)

#define ASSERT_TRUE(cond) \
    if (!(cond)) throw std::runtime_error("Assertion failed: " #cond)

#define ASSERT_EQ(a, b) \
    if ((a) != (b)) throw std::runtime_error(                       \
        std::string("Assertion failed: ") + #a + " != " + #b)

// ===================== TESTS =====================

using namespace netwatch::protocol;

// Test 1: encode produces correct frame size
void test_encode_size()
{
    std::string payload = "hello";
    std::string frame = encode(payload);
    // Frame should be 4-byte header + payload
    ASSERT_EQ(frame.size(), static_cast<size_t>(4 + payload.size()));
}

// Test 2: encode header contains correct network-order length
void test_encode_header_value()
{
    std::string payload = "test message";
    std::string frame = encode(payload);

    uint32_t encoded_len = 0;
    std::memcpy(&encoded_len, frame.data(), 4);
    uint32_t decoded_len = ntohl(encoded_len);

    ASSERT_EQ(decoded_len, static_cast<uint32_t>(payload.size()));
}

// Test 3: encode body matches original payload
void test_encode_body()
{
    std::string payload = "{\"type\":\"heartbeat\"}";
    std::string frame = encode(payload);
    std::string body = frame.substr(4);
    ASSERT_EQ(body, payload);
}

// Test 4: decodeHeader extracts the correct length from an encoded frame
void test_decode_header()
{
    std::string payload = "some data here";
    std::string frame = encode(payload);
    uint32_t len = decodeHeader(frame.data());
    ASSERT_EQ(len, static_cast<uint32_t>(payload.size()));
}

// Test 5: encode/decode roundtrip with empty payload
void test_empty_payload()
{
    std::string payload = "";
    std::string frame = encode(payload);
    ASSERT_EQ(frame.size(), static_cast<size_t>(4));
    
    uint32_t len = decodeHeader(frame.data());
    ASSERT_EQ(len, static_cast<uint32_t>(0));
}

// Test 6: encode/decode roundtrip with large payload
void test_large_payload()
{
    std::string payload(100000, 'X');
    std::string frame = encode(payload);
    
    uint32_t len = decodeHeader(frame.data());
    ASSERT_EQ(len, static_cast<uint32_t>(payload.size()));

    std::string body = frame.substr(4);
    ASSERT_EQ(body, payload);
}

// Test 7: MessageType toString
void test_to_string()
{
    ASSERT_EQ(toString(MessageType::Heartbeat),    std::string("Heartbeat"));
    ASSERT_EQ(toString(MessageType::SystemStats),  std::string("SystemStats"));
    ASSERT_EQ(toString(MessageType::ProcessList),  std::string("ProcessList"));
    ASSERT_EQ(toString(MessageType::Unknown),      std::string("Unknown"));
}

// Test 8: MessageType fromString
void test_from_string()
{
    ASSERT_TRUE(fromString("Heartbeat")   == MessageType::Heartbeat);
    ASSERT_TRUE(fromString("SystemStats") == MessageType::SystemStats);
    ASSERT_TRUE(fromString("ProcessList") == MessageType::ProcessList);
    ASSERT_TRUE(fromString("garbage")     == MessageType::Unknown);
    ASSERT_TRUE(fromString("")            == MessageType::Unknown);
}

// Test 9: roundtrip toString -> fromString
void test_roundtrip_type_conversion()
{
    auto check = [](MessageType t) {
        ASSERT_TRUE(fromString(toString(t)) == t);
    };

    check(MessageType::Heartbeat);
    check(MessageType::SystemStats);
    check(MessageType::ProcessList);
    check(MessageType::Unknown);
}

// Test 10: multiple sequential encode/decode cycles
void test_multiple_frames()
{
    std::vector<std::string> payloads = {
        "first",
        "second message",
        "{\"key\":\"value\",\"num\":42}",
        std::string(500, 'Z')
    };

    for (const auto& payload : payloads)
    {
        std::string frame = encode(payload);
        uint32_t len = decodeHeader(frame.data());
        ASSERT_EQ(len, static_cast<uint32_t>(payload.size()));
        
        std::string body = frame.substr(4);
        ASSERT_EQ(body, payload);
    }
}

// ===================== MAIN =====================

int main()
{
    std::cout << "=== Protocol Tests ===\n";

    RUN_TEST(test_encode_size);
    RUN_TEST(test_encode_header_value);
    RUN_TEST(test_encode_body);
    RUN_TEST(test_decode_header);
    RUN_TEST(test_empty_payload);
    RUN_TEST(test_large_payload);
    RUN_TEST(test_to_string);
    RUN_TEST(test_from_string);
    RUN_TEST(test_roundtrip_type_conversion);
    RUN_TEST(test_multiple_frames);

    std::cout << "\n--- Results: " 
              << tests_passed << " passed, " 
              << tests_failed << " failed ---\n";

    return tests_failed == 0 ? 0 : 1;
}
